[package]
name = "liqpay_rs"
version = "0.1.0"
edition = "2024"

[features]
blocking = ["reqwest/blocking"]

[dependencies]
base64 = "0.22.1"
iso3166 = "1.2.1"
reqwest = { version = "0.12.22", features = ["json", "blocking"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha1 = "0.10.6"
sha3 = "0.10.8"
